# Generated by Django 3.2.17 on 2023-02-24 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0001_initial'),
        ('matches', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='seeker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Seekers', to='seekers.seekeruserprofile'),
        ),
    ]
