# Generated by Django 3.2.17 on 2023-03-05 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0008_auto_20230305_1622'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seekers', '0005_auto_20230305_1622'),
        ('matches', '0003_alter_match_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Advisors', to='advisors.advisoruserprofile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='seeker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Seekers', to='seekers.seekeruserprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match', to='matches.match'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
