# Generated by Django 3.2.17 on 2023-03-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20230305_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_client',
        ),
    ]
