# Generated by Django 3.2.17 on 2023-03-07 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0005_auto_20230305_1622'),
        ('matches', '0005_remove_match_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='seeker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Seekers', to='seekers.seekeruserprofile'),
        ),
    ]
