# Generated by Django 3.2.17 on 2023-03-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_match_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='matches.match'),
        ),
    ]
