# Generated by Django 3.2.17 on 2023-02-10 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('street_address', models.CharField(max_length=80)),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='home.specialisation')),
                ('town_or_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='home.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seekers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
