# Generated by Django 3.2.17 on 2023-03-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0002_auto_20230304_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekeruserprofile',
            name='postcode',
            field=models.CharField(blank=True, default=44, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seekeruserprofile',
            name='street_address',
            field=models.CharField(blank=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
