# Generated by Django 3.2.17 on 2023-02-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_consultation_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='created_on',
            new_name='created',
        ),
    ]
