# Generated by Django 3.2.17 on 2023-02-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_rename_created_on_consultation_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not confirmed'), (1, 'Confirmed')], default=0),
        ),
    ]
