# Generated by Django 3.2.17 on 2023-03-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20230305_1622'),
        ('consultations', '0005_consultation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation', to='matches.match'),
        ),
    ]
