# Generated by Django 3.2.17 on 2023-03-05 17:40

import consultations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_alter_consultation_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateField(validators=[consultations.models.validate_date]),
        ),
    ]
