# Generated by Django 3.2.17 on 2023-03-05 17:44

import consultations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_alter_consultation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='time',
            field=models.TimeField(validators=[consultations.models.validate_date]),
        ),
    ]
