# Generated by Django 3.2.17 on 2023-03-05 17:51

import consultations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_auto_20230305_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateField(validators=[consultations.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='time',
            field=models.TimeField(),
        ),
    ]
