# Generated by Django 3.2.17 on 2023-03-04 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile_phone_number'),
        ('checkout', '0003_rename_first_name_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='town_or_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='home.location'),
        ),
    ]
