# Generated by Django 3.2.17 on 2023-03-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_userprofile_user'),
        ('checkout', '0007_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='town_or_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='home.location'),
        ),
    ]
