# Generated by Django 3.2.17 on 2023-03-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
