# Generated by Django 3.2.17 on 2023-03-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(choices=[(0, "I'm a financial advisor"), (1, "I'm looking for advice")]),
        ),
    ]
