# Generated by Django 3.2.17 on 2023-02-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0002_auto_20230209_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisoruserprofile',
            name='registration_number',
            field=models.CharField(default=444445678, max_length=100),
            preserve_default=False,
        ),
    ]
