# Generated by Django 3.2.17 on 2023-02-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('advisors', '0003_advisoruserprofile_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisoruserprofile',
            name='specialisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialisations', to='home.specialisation'),
        ),
        migrations.AlterField(
            model_name='advisoruserprofile',
            name='town_or_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='home.location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Specialisation',
        ),
    ]
