# Generated by Django 3.2.17 on 2023-02-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0005_auto_20230211_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisoruserprofile',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
