# Generated by Django 3.2.17 on 2023-02-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0006_alter_advisoruserprofile_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisoruserprofile',
            name='approved',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'not approved')], default=0),
        ),
    ]
