# Generated by Django 3.2.17 on 2023-03-05 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advisors', '0007_alter_advisoruserprofile_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisoruserprofile',
            name='specialisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialisations', to='home.specialisation'),
        ),
        migrations.AlterField(
            model_name='advisoruserprofile',
            name='town_or_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='home.location'),
        ),
        migrations.AlterField(
            model_name='advisoruserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
